# Generated by Django 5.0 on 2023-12-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sihapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('depth_md', models.FloatField()),
                ('x_location', models.FloatField()),
                ('y_location', models.FloatField()),
                ('z_location', models.FloatField()),
                ('bulk_density', models.FloatField()),
                ('borehole_size', models.FloatField()),
                ('avg_rate_of_penetration', models.FloatField()),
                ('density_correction_log', models.FloatField()),
                ('wt_of_drilling_mud', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='requireddata',
            name='image_data',
        ),
        migrations.DeleteModel(
            name='ImageData',
        ),
        migrations.DeleteModel(
            name='RequiredData',
        ),
    ]
